#!/usr/bin/env python3
"""
CounterHarm Evaluation Metrics
D-PURiFY | DIA-GUARD -> Dia-LLM

Evaluates the quality of benign counterexamples generated by CounterHarm-SHIELD.
Compares each counterharm output against its source to measure:

1. BERTScore     - Contextual embedding similarity (structural/surface similarity)
2. Semantic Sim  - Sentence-transformer cosine similarity (meaning relatedness)
3. NLI Score     - Natural Language Inference (entailment vs contradiction)
                   Shows the content shift from harmful source to benign output.

Column pairs evaluated:
    counterharm_original   <-> original_input
    counterharm_transformed <-> transformed_input
    counterharm_basic      <-> basic_transform
    counterharm_coi        <-> coi_transform
"""

import torch
import pandas as pd
import numpy as np
from typing import List, Optional, Dict, Tuple

POLICY_VIOLATION = "guardrail policy violation"

# Source -> CounterHarm output column mapping
SOURCE_TO_COUNTERHARM = {
    "original_input": "counterharm_original",
    "transformed_input": "counterharm_transformed",
    "basic_transform": "counterharm_basic",
    "coi_transform": "counterharm_coi",
}

# Batch sizes for T4 16GB
BATCH_SIZES = {
    "BERTScore": 128,
    "SemanticSim": 128,
    "NLI": 64,
}


class CounterHarmMetrics:
    """Evaluation metrics for CounterHarm-SHIELD benign counterexamples.

    Measures the difference between harmful source text and its benign
    counterpart across three dimensions:

    - BERTScore: Surface/structural similarity (high = similar phrasing)
    - Semantic Similarity: Meaning relatedness (moderate = topic overlap)
    - NLI: Entailment score (low = successful content shift from harmful to benign)

    Expected patterns for good counterexamples:
    - BERTScore: moderate (0.3-0.6) — similar structure, different content
    - Semantic Sim: moderate (0.3-0.6) — related topic, different intent
    - NLI Entailment: low (<0.3) — benign should NOT entail harmful
    - NLI Contradiction: high (>0.5) — benign should contradict harmful intent
    """

    def __init__(self, device: Optional[str] = None, batch_sizes: Optional[dict] = None):
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.batch_sizes = batch_sizes or BATCH_SIZES
        self._models = {}
        print(f"[D-PURiFY | CounterHarm] Using device: {self.device}")

    def _load_bertscore(self):
        if "bertscore" not in self._models:
            from bert_score import BERTScorer
            self._models["bertscore"] = BERTScorer(
                model_type="microsoft/deberta-xlarge-mnli",
                device=self.device,
                batch_size=self.batch_sizes["BERTScore"],
                rescale_with_baseline=True,
                lang="en",
            )
        return self._models["bertscore"]

    def _load_semantic_model(self):
        if "semantic" not in self._models:
            from sentence_transformers import SentenceTransformer
            self._models["semantic"] = SentenceTransformer(
                "all-mpnet-base-v2", device=self.device
            )
        return self._models["semantic"]

    def _load_nli_model(self):
        if "nli" not in self._models:
            from transformers import AutoModelForSequenceClassification, AutoTokenizer
            model_name = "cross-encoder/nli-deberta-v3-base"
            self._models["nli_tokenizer"] = AutoTokenizer.from_pretrained(model_name)
            self._models["nli_model"] = AutoModelForSequenceClassification.from_pretrained(
                model_name
            ).to(self.device)
            self._models["nli_model"].eval()
            # Labels: 0=contradiction, 1=entailment, 2=neutral
        return self._models["nli_model"], self._models["nli_tokenizer"]

    def compute_bertscore(self, sources: List[str], counterharms: List[str]) -> List[float]:
        """Compute BERTScore F1 between source and counterharm output."""
        scorer = self._load_bertscore()
        P, R, F1 = scorer.score(counterharms, sources)
        return F1.cpu().numpy().tolist()

    def compute_semantic_similarity(self, sources: List[str], counterharms: List[str]) -> List[float]:
        """Compute cosine similarity using sentence-transformers (all-mpnet-base-v2)."""
        model = self._load_semantic_model()
        batch_size = self.batch_sizes["SemanticSim"]

        src_emb = model.encode(sources, batch_size=batch_size, show_progress_bar=False)
        ch_emb = model.encode(counterharms, batch_size=batch_size, show_progress_bar=False)

        from sklearn.metrics.pairwise import cosine_similarity
        scores = [
            float(cosine_similarity([s], [c])[0][0])
            for s, c in zip(src_emb, ch_emb)
        ]
        return scores

    def compute_nli(
        self, sources: List[str], counterharms: List[str]
    ) -> Tuple[List[float], List[float], List[float]]:
        """Compute NLI scores (entailment, contradiction, neutral).

        Premise: source (harmful text)
        Hypothesis: counterharm (benign text)

        Returns:
            (contradiction_scores, entailment_scores, neutral_scores)

        For good counterexamples:
            - High contradiction: benign text contradicts harmful intent
            - Low entailment: benign does not logically follow from harmful
        """
        model, tokenizer = self._load_nli_model()
        batch_size = self.batch_sizes["NLI"]

        contradictions = []
        entailments = []
        neutrals = []

        for i in range(0, len(sources), batch_size):
            batch_src = sources[i : i + batch_size]
            batch_ch = counterharms[i : i + batch_size]

            inputs = tokenizer(
                batch_src,
                batch_ch,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512,
            ).to(self.device)

            with torch.no_grad():
                outputs = model(**inputs)
                probs = torch.softmax(outputs.logits, dim=-1).cpu().numpy()

            # Labels: 0=contradiction, 1=entailment, 2=neutral
            for p in probs:
                contradictions.append(float(p[0]))
                entailments.append(float(p[1]))
                neutrals.append(float(p[2]))

        return contradictions, entailments, neutrals

    def compute_all_for_pair(
        self, sources: List[str], counterharms: List[str], prefix: str = "ch_original"
    ) -> dict:
        """Compute all counterharm metrics for a single source-output pair.

        Args:
            sources: List of source texts (harmful)
            counterharms: List of counterharm outputs (benign)
            prefix: Column name prefix (e.g., 'ch_original', 'ch_transformed')

        Returns:
            Dict of column_name -> scores
        """
        results = {}

        print(f"    Computing BERTScore ({prefix})...")
        results[f"{prefix}_bertscore"] = self.compute_bertscore(sources, counterharms)

        print(f"    Computing Semantic Similarity ({prefix})...")
        results[f"{prefix}_semantic_sim"] = self.compute_semantic_similarity(sources, counterharms)

        print(f"    Computing NLI ({prefix})...")
        contradiction, entailment, neutral = self.compute_nli(sources, counterharms)
        results[f"{prefix}_nli_contradiction"] = contradiction
        results[f"{prefix}_nli_entailment"] = entailment
        results[f"{prefix}_nli_neutral"] = neutral

        return results

    def evaluate_csv(self, df: pd.DataFrame) -> pd.DataFrame:
        """Evaluate all counterharm columns in a DataFrame.

        Processes each source-counterharm pair:
            original_input     -> counterharm_original
            transformed_input  -> counterharm_transformed
            basic_transform    -> counterharm_basic
            coi_transform      -> counterharm_coi

        Skips rows where source or counterharm is empty/policy violation.
        """
        for src_col, ch_col in SOURCE_TO_COUNTERHARM.items():
            if ch_col not in df.columns or src_col not in df.columns:
                continue

            prefix = f"ch_{ch_col.replace('counterharm_', '')}"

            # Skip if already computed
            if f"{prefix}_bertscore" in df.columns:
                print(f"  Skipping {prefix} (already computed)")
                continue

            # Find valid rows (both source and counterharm present, not policy violation)
            valid_mask = (
                df[src_col].fillna("").astype(str).str.strip().ne("")
                & df[src_col].fillna("").astype(str).str.strip().ne(POLICY_VIOLATION)
                & df[ch_col].fillna("").astype(str).str.strip().ne("")
                & df[ch_col].fillna("").astype(str).str.strip().ne(POLICY_VIOLATION)
                & df[ch_col].fillna("").astype(str).str.strip().ne("[FAILED]")
            )

            valid_count = valid_mask.sum()
            if valid_count == 0:
                print(f"  Skipping {prefix} (no valid pairs)")
                continue

            print(f"\n  Evaluating {prefix}: {valid_count} valid pairs")

            sources = df.loc[valid_mask, src_col].astype(str).tolist()
            counterharms = df.loc[valid_mask, ch_col].astype(str).tolist()

            metrics = self.compute_all_for_pair(sources, counterharms, prefix=prefix)

            # Write scores back, NaN for invalid rows
            for col_name, scores in metrics.items():
                df[col_name] = np.nan
                df.loc[valid_mask, col_name] = scores

        return df

    def cleanup(self):
        """Free GPU memory."""
        self._models.clear()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
