compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: auto
  gradient_clipping: auto
  zero_optimization:
    stage: 2
    overlap_comm: true
    contiguous_gradients: true
    reduce_scatter: true
    reduce_bucket_size: 5.0e+08
    allgather_bucket_size: 5.0e+08
  zero3_init_flag: false
  zero3_save_16bit_model: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
